apiVersion: v1
kind: Service
metadata:
  name:  service-for-test
spec:
  type: ClusterIP
  selector:
      app: nginx
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
      