apiVersion: v1
kind: Pod
metadata:
  name: pod-ip-env-pod
spec:
  containers:
  - name: pod-ip-env-container
    image: busybox
    command: ['sh', '-c', 'echo $(MY_POD_IP) && sleep 3600']
    env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
