apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-backup-job
spec:
  template:
    spec:
      containers:
      - name: backup
        image: mongo:latest
        command: ["sh", "-c", "mongodump --uri=mongodb://mongodb:27017/mydatabase --out=/backup && echo Backup completed!"]
        volumeMounts:
        - name: backup-storage
          mountPath: /backup
      restartPolicy: OnFailure
      volumes:
      - name: backup-storage
        persistentVolumeClaim:
          claimName: backup-pvc
  backoffLimit: 4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi