apiVersion: batch/v1
kind: Job
metadata:
  name: data-processor-job
spec:
  template:
    spec:
      containers:
      - name: data-processor
        image: busybox
        command: ["sh", "-c", "echo Processing data...; sleep 10; echo Data processed!"]
      restartPolicy: OnFailure
  backoffLimit: 4